#!/usr/bin/env ruby

require "json"

def submit_pr(dir)
  branch_name = "normalize-config"
  if system "git branch | grep -q %s" % branch_name
    puts "skipping %s. Already has an %s branch." % [dir, branch_name]
    return
  end

  system "git reset --hard && git checkout master && git pull --rebase origin master"
  config = JSON.parse(File.read('config.json'))
  File.open('config.json', 'w') do |f|
    f.puts JSON.pretty_generate(config)
  end

  if !system('git status | grep -q config.json')
    puts "skipping %s. Config is already normalized." % dir
    return
  end

  msg = "Normalize format of config file\n\n This will let us script changes to it with less noise in the diffs."

  system "git checkout -b %s" % branch_name
  system "git add config.json"
  system "git commit -m '%s'" % msg
  system "git push origin %s" % branch_name
  system "hub pull-request -m '%s'" % msg
  sleep 4
end

pwd = Dir.pwd
Dir.glob("./tracks/*").each do |dir|
  Dir.chdir(dir)

  submit_pr(dir)

  Dir.chdir(pwd)
end
